global proc batchMocap()
{
	source ltExport.mel;


	if(`window -ex BatchMocapUI`)
 		deleteUI BatchMocapUI; 

	if(!`optionVar -ex st_batchMocapSourcePath`)
		optionVar -sv st_batchMocapSourcePath "//Cluge/D/Softimage/Motion_Capture/NOLF2/";
	if(!`optionVar -ex st_batchMocapDestPath`)
		optionVar -sv st_batchMocapDestPath "C:/MocapArchive/NOLF2/";

	window
 		-menuBar false 
 		-maximizeButton false 
		-sizeable 1 
		-w 5//$ui_Width 
		-h 5//$ui_Height
 		-rtf 1 
		-title "ScottTech2000"
 		BatchMocapUI;

	columnLayout;
 		frameLayout
 			-label "Batch Process Mocap"
 			-w (420)
 			-h (70);
			columnLayout;	
 				textFieldButtonGrp 
 					-cw 1 60 
 					-cw 2 300 
 					-label "In Path:"
  					-fi `optionVar -q st_batchMocapSourcePath`
					-cc 	"optionVar -sv st_batchMocapSourcePath (`textFieldGrp -q -text st_SourcePath`)"

 					-buttonLabel "Browse..."
  					st_SourcePath;
  				textFieldButtonGrp
					-cw 1 60
					-cw 2 300
					-label "Out Path:"
					-fi `optionVar -q st_batchMocapDestPath`
					-cc 	"optionVar -sv st_batchMocapDestPath (`textFieldGrp -q -text st_DestPath`)"

  					-buttonLabel "Browse..."
					st_DestPath;
			setParent ..;
		setParent ..;
		rowLayout
 			-numberOfColumns 2
 			-rat 1 "top" 2
 			-rat 2 "top" 2
 			-columnWidth 1 200;
 			button  -label "Process" -w 150 -h 30 -c "doBatchMocap";
 			button  -label "Close"  -w 150 -h 30 -c "deleteUI BatchMocapUI";
 		setParent ..;
 	setParent ..;
	showWindow BatchMocapUI;
}

global proc doBatchMocap()
{
	int $i, $numFrames;
	string $filename, $buffer[];
	string $inPath = `textFieldGrp -q -text st_SourcePath`;
	string $outPath = `textFieldGrp -q -text st_DestPath`;

	tokenize($outPath, "\\", $buffer);
	$destPath = $buffer[0] + "/";
	for($i = 1; $i < size($buffer); $i++) 
		$destPath = $destPath + $buffer[$i] + "/";

	string $fileList[] = `getFileList -folder $inPath -fs "*.htr"`;
	
	int $animNumber = 1;
	int $ltaNumber = 0;
	for($i = 0; $i < size($fileList); $i++)
	{
		tokenize($fileList[$i], ".", $buffer);
		$filename = $buffer[0];
	
		if(!`file -q -ex ($destPath + $filename + ".mb")`)
		{
			if($animNumber > 25)
			{	
				$animNumber = 0;
				$ltaNumber++;
			}
			$numFrames = `readHTR ($inPath + $fileList[$i])`;
			playbackOptions -min 0 -max $numFrames;
			currentTime 0; currentTime 1; currentTime 0;
		//	exportMocapLTA $destPath $filename $ltaNumber;
	
			file -rename ($destPath + $filename + ".mb");
			file -f -save -options "v=0" -type "mayaBinary";
			file -new;
			$animNumber++;
		}
	}
	if(`window -ex BatchMocapUI`)
		deleteUI BatchMocapUI;	
}

global proc exportMocapLTA(string $path, string $animName, int $index)
{
	string $buffer[];
	$savedAnimName = `optionVar -q lt_defaultAnimName`;
	$savedTimeRangeStatus = `optionVar -q lt_defaultTimeRangeStatus`;
	$savedAppendStatus = `optionVar -q lt_defaultAppendStatus`;

	optionVar -sv lt_defaultAnimName $animName;
	optionVar -iv lt_defaultTimeRangeStatus 0;
	optionVar -iv lt_defaultAppendStatus 1;

	tokenize($path,"/",$buffer);
	$file = $buffer[size($buffer)-1];
	$filename = $path + $file + "Mocap" + $index + ".lta";

	if(`file -q -ex $filename`)
		ltaExportNoAppend $filename 1;
	else if(!(`file -q -ex $filename`))
		ltaExportNoAppend $filename 0;

	optionVar -sv lt_defaultAnimName $savedAnimName;
	optionVar -iv lt_defaultTimeRangeStatus $savedTimeRangeStatus;
	optionVar -iv lt_defaultAppendStatus $savedAppendStatus;
}
