/*
	This script will copy animations from one skeleton to another
	under very specific (but useful) conditions.  The source skeleton 
	must have the hierarchy of mocap imported using my version of readHTR.mel.
	The destination must also have this form at the top of the hierarchy, 
	but can also have any number additional joints below this.

	Basically it copies mocap onto any skelton the is based on the mocap skeleton.

	To use, select the source root, then the destination root and run the script.

*/

global proc copyAnim()
{
	int $i=0;
	float $keyTimes[];
	string $toSkeleton[], $transInput[], $rotInput[];

	$selection = `ls -sl`;
	$fromRoot = $selection[0];
	$toRoot = $selection[1];


	if(`objExists ($fromRoot + ".animName")`)
	{
		if(!`objExists ($toRoot + ".animName")`)
			addAttr -ln "animName" -dt "string" $toRoot;
		setAttr ($toRoot + ".animName") -type "string" (`getAttr ($fromRoot + ".animName")`);
	}


	if(`objExists ($fromRoot + ".keyTimes")`)
	{
		if(!`objExists ($toRoot + ".keyTimes")`)
			addAttr -ln "keyTimes" -dt "string" $toRoot;
		setAttr ($toRoot + ".keyTimes") -type "string" (`getAttr ($fromRoot + ".keyTimes")`);
	}
	if ((!`objExists ($fromRoot + ".keyTimes")`) && (`objExists ($toRoot + ".keyTimes")`))
		deleteAttr ($toRoot + ".keyTimes");

	if (`objExists ($fromRoot + ".modelStrings")`)
	{
		if(!`objExists ($toRoot + ".modelStrings")`)
			addAttr -ln "modelStrings" -dt "string" $toRoot;
		setAttr ($toRoot + ".modelStrings") -type "string" (`getAttr ($fromRoot + ".modelStrings")`);
	}
	if ((!`objExists ($fromRoot + ".modelStrings")`) && (`objExists ($toRoot + ".modelStrings")`))
		deleteAttr ($toRoot + ".modelStrings");

	if(`objExists ($fromRoot + ".interpolation")`)
	{
		if(!`objExists ($toRoot + ".interpolation")`)
			addAttr -ln "interpolation" -at "float" $toRoot;
		setAttr ($toRoot + ".interpolation") (`getAttr ($fromRoot + ".interpolation")`);
	}

	if(`objExists ($fromRoot + ".translation")`)
	{
		if(!`objExists ($toRoot + ".translation")`)
			addAttr -ln "translation" -dt "string" $toRoot;
		setAttr ($toRoot + ".translation") -type "string" (`getAttr ($fromRoot + ".translation")`);
	}

	
	select -r -hi $toRoot;
	$keySkel = `ls -sl -l`;
	for($i = 0; $i < size($keySkel); $i++)
	{
		$transInput = `listConnections -t animCurveTL $keySkel[$i]`;
		$rotInput = `listConnections -t animCurveTA $keySkel[$i]`;
		if(($rotInput[0]!="") || ($transInput[0]!=""))
		{
			$cmd = "cutKey -clear -time \":\" -hierarchy none -controlPoints 0 -shape 1 {\"" + $keySkel[$i] + "\"}";
			eval($cmd);
		}
	}

	$i=0;
	select -r -hi $fromRoot;
	$fromSkel = `ls -sl -type joint`;
	$numJoints = size($fromSkel);
	select -cl;
			
	pointConstraint $fromRoot $toRoot;
	orientConstraint $fromRoot $toRoot;
	$toSkeleton[$i] = $toRoot;  $i++;

	$fromParent = $fromRoot;
	$toParent = $toRoot;
	$fromChild = `listRelatives -c -f $fromParent`;
	$toChild = `listRelatives -c -f $toParent`;

	pointConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;
	$fromParent = $fromChild[0];
	$toParent = $toChild[0];
//print ($fromChild[0] + "\n");
	$keyTimes = `keyframe -q -tc $fromChild[0]`;
//print (size($keyTimes));
	if(size($keyTimes) != 0 )
		playbackOptions -minTime ($keyTimes[0]) -maxTime ($keyTimes[(size($keyTimes))-1]);
	else
		playbackOptions -minTime ($keyTimes[0]) -maxTime ($keyTimes[0] + 1);

	$fromChild = `listRelatives -c -f $fromParent`;
	$toChild = `listRelatives -c -f $toParent`;

	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;
	orientConstraint $fromChild[1] $toChild[1];
	$toSkeleton[$i] = $toChild[1];  $i++;
	orientConstraint $fromChild[2] $toChild[2];
	$toSkeleton[$i] = $toChild[2];  $i++;

	$fromParent1 = $fromChild[0];
	$toParent1 = $toChild[0];
	$fromParent2 = $fromChild[1];
	$toParent2 = $toChild[1];
	$fromParent3 = $fromChild[2];
	$toParent3 = $toChild[2];
	
	$fromChild = `listRelatives -c -f $fromParent1`;
	$toChild = `listRelatives -c -f $toParent1`;

	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;
	$fromParent1 = $fromChild[0];
	$toParent1 = $toChild[0];

	$fromChild = `listRelatives -c -f $fromParent1`;
	$toChild = `listRelatives -c -f $toParent1`;

	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;
	orientConstraint $fromChild[1] $toChild[1];
	$toSkeleton[$i] = $toChild[1];  $i++;
	orientConstraint $fromChild[2] $toChild[2];
	$toSkeleton[$i] = $toChild[2];  $i++;


	$fromParent11 = $fromChild[0];
	$toParent11 = $toChild[0];
	$fromParent12 = $fromChild[1];
	$toParent12 = $toChild[1];
	$fromParent13 = $fromChild[2];
	$toParent13 = $toChild[2];

	$fromChild = `listRelatives -c -f $fromParent11`;
	$toChild = `listRelatives -c -f $toParent11`;
	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;

	$fromChild = `listRelatives -c -f $fromParent12`;
	$toChild = `listRelatives -c -f $toParent12`;
	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;
	$fromParent12 = $fromChild[0];
	$toParent12 = $toChild[0];

	$fromChild = `listRelatives -c -f $fromParent12`;
	$toChild = `listRelatives -c -f $toParent12`;
	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;
	$fromParent12 = $fromChild[0];
	$toParent12 = $toChild[0];

	$fromChild = `listRelatives -c -f $fromParent12`;
	$toChild = `listRelatives -c -f $toParent12`;
	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;


	$fromChild = `listRelatives -c -f $fromParent13`;
	$toChild = `listRelatives -c -f $toParent13`;
	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;
	$fromParent13 = $fromChild[0];
	$toParent13 = $toChild[0];

	$fromChild = `listRelatives -c -f $fromParent13`;
	$toChild = `listRelatives -c -f $toParent13`;
	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;
	$fromParent13 = $fromChild[0];
	$toParent13 = $toChild[0];

	$fromChild = `listRelatives -c -f $fromParent13`;
	$toChild = `listRelatives -c -f $toParent13`;
	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;

	$fromChild = `listRelatives -c -f $fromParent2`;
	$toChild = `listRelatives -c -f $toParent2`;
	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;
	$fromParent2 = $fromChild[0];
	$toParent2 = $toChild[0];

	$fromChild = `listRelatives -c -f $fromParent2`;
	$toChild = `listRelatives -c -f $toParent2`;
	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;
	$fromParent2 = $fromChild[0];
	$toParent2 = $toChild[0];

	$fromChild = `listRelatives -c -f $fromParent2`;
	$toChild = `listRelatives -c -f $toParent2`;
	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;

	$fromChild = `listRelatives -c -f $fromParent3`;
	$toChild = `listRelatives -c -f $toParent3`;
	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;
	$fromParent3 = $fromChild[0];
	$toParent3 = $toChild[0];

	$fromChild = `listRelatives -c -f $fromParent3`;
	$toChild = `listRelatives -c -f $toParent3`;
	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;
	$fromParent3 = $fromChild[0];
	$toParent3 = $toChild[0];

	$fromChild = `listRelatives -c -f $fromParent3`;
	$toChild = `listRelatives -c -f $toParent3`;
	orientConstraint $fromChild[0] $toChild[0];
	$toSkeleton[$i] = $toChild[0];  $i++;



	
	
	string $fromMovement[] = `listRelatives -c -f $fromSkel[(size($fromSkel))-1]`;
	string $toMovement[] = `listRelatives -c -f $toSkeleton[0]`;

	if( (size($fromMovement) > 1) && (size($toMovement) > 1) )
	{
		if( (`gmatch $fromMovement[1] "*movement*"`) && (`gmatch $toMovement[1] "*movement*"`) )
		{
			if(`copyKey $fromMovement[1]`)
				pasteKey $toMovement[1];
		}
	}





	select -r $toSkeleton; //return;
	bakeAnim;

//	select -r $fromSkel;
//	delete -constraints;

	select -cl;
}



global proc string[] getInput(string $output[])
{
	string $input[];
	$driver = `listConnections -type orientConstraint -type pointConstraint`;
	print $driver;

	return $input;
}


global proc bakeAnim() 
{
	int $vis[];
	float $keyTime[];
	string $tmp[], $orientTarget[], $pointTarget[];

	$sceneShapes = `ls -ni -type mesh`;
	for($i = 0; $i < size($sceneShapes); $i++)
	{
		$obj = `listRelatives -f -p $sceneShapes[$i]`;
		$sceneShapes[$i] = $obj[0];
		$vis[$i] = `getAttr ($sceneShapes[$i] + ".visibility")`;
		setAttr ($sceneShapes[$i] + ".visibility") 0;
	}


	
	
	$outputSkel = `ls -sl`;
	$tmp = (`pointConstraint -q -tl $outputSkel[0]`); 
	$inputSkel[0] = $tmp[0];
	delete -constraints $inputSkel[0];
	if(`copyKey $inputSkel[0]`)
		pasteKey $outputSkel[0];

	$tmp = (`pointConstraint -q -tl $outputSkel[1]`); 
	$inputSkel[1] = $tmp[0];
	delete -constraints $inputSkel[1];
	if(`copyKey $inputSkel[1]`)
		pasteKey $outputSkel[1];

	for($i = 2; $i < size($outputSkel); $i++)
	{
		$tmp = (`orientConstraint -q -tl $outputSkel[$i]`); 
		$inputSkel[$i] = $tmp[0];

		delete -constraints $inputSkel[$i];
		if(`copyKey $inputSkel[$i]`)
			pasteKey $outputSkel[$i];
	}
	


/*	$outputSkel = `ls -sl`;
	$tmp = (`pointConstraint -q -tl $outputSkel[0]`); 
	select -tgl $tmp[0];
	$tmp = (`pointConstraint -q -tl $outputSkel[1]`); 
	select -tgl $tmp[0];

	for($i = 2; $i < size($outputSkel); $i++)
		select -add (`orientConstraint -q -tl $outputSkel[$i]`); 
*/
	
	
/*	
	int $j = 1;
	$keyTime[0] = -9999;
	float $minTime = `playbackOptions -q -minTime`;
	float $maxTime = `playbackOptions -q -maxTime`;
	$cmd = "bakeResults -simulation true -an \"keysOrObjects\" ";
	$cmd = $cmd + " -t \"" + $minTime + ":" + $maxTime + "\"";

	while($keyTime[$j] > $keyTime[$j-1])
	{
//		$cmd = $cmd + " -t " + $keyTime[$j] + " ";
		
		$j++;
		$keyTime[$j] = `findKeyframe -time $keyTime[$j-1] -which next`;
	}
	$cmd = $cmd + " -sb " + $keyTime[2] + " -iub 1";

	print ($cmd + "\n");
	eval $cmd;
*/



/*
 	int $rate = 1; ///`intField -q -v sb_sampleRate`; 	
	optionVar -fv "bakeSimulationByTime" $rate; 	
	BakeSimulation; 
*/
	
	delete -staticChannels; 


	for($i = 0; $i < size($sceneShapes); $i++)
	{
		setAttr ($sceneShapes[$i] + ".visibility") $vis[$i];
	}

	$selection = `ls -sl`;
	string $cmd = "filterCurve ";
	for($i = 0; $i < size($selection); $i++)
	{
		if(`objExists ($selection[$i] + ".rotateX")`)
			$cmd = $cmd+ $selection[$i] + ".rotateX ";
		if(`objExists ($selection[$i] + ".rotateY")`)
			$cmd = $cmd+ $selection[$i] + ".rotateY ";
		if(`objExists ($selection[$i] + ".rotateZ")`)
			$cmd = $cmd+ $selection[$i] + ".rotateZ ";
	}
	eval($cmd);
}


global proc bake() 
{
	int $vis[];
	float $keyTime[];
	string $tmp[], $orientTarget[], $pointTarget[];

	$sceneShapes = `ls -ni -type mesh`;
	for($i = 0; $i < size($sceneShapes); $i++)
	{
		$obj = `listRelatives -f -p $sceneShapes[$i]`;
		$sceneShapes[$i] = $obj[0];
		$vis[$i] = `getAttr ($sceneShapes[$i] + ".visibility")`;
		setAttr ($sceneShapes[$i] + ".visibility") 0;
	}


 	int $rate = 1; ///`intField -q -v sb_sampleRate`; 	
	optionVar -fv "bakeSimulationByTime" $rate; 	
	BakeSimulation; 

	
	delete -staticChannels; 


	for($i = 0; $i < size($sceneShapes); $i++)
	{
		setAttr ($sceneShapes[$i] + ".visibility") $vis[$i];
	}

	$selection = `ls -sl`;
	string $cmd = "filterCurve ";
	for($i = 0; $i < size($selection); $i++)
	{
		if(`objExists ($selection[$i] + ".rotateX")`)
			$cmd = $cmd+ $selection[$i] + ".rotateX ";
		if(`objExists ($selection[$i] + ".rotateY")`)
			$cmd = $cmd+ $selection[$i] + ".rotateY ";
		if(`objExists ($selection[$i] + ".rotateZ")`)
			$cmd = $cmd+ $selection[$i] + ".rotateZ ";
	}
	eval($cmd);
}