/*
	LTA/LTC Exporter

	Requires ltaImport.mel to be fully functional.

*/
global proc string getSceneName()
{
	string $buffer[], $textureIndex;
	string $sceneName = `file -q -sn`;
	tokenize($sceneName, ".", $buffer);
	string $scenePath = $buffer[0];
	tokenize($scenePath, "/", $buffer);
	string $scene = $buffer[size($buffer)-1];

	return $scene;
}

global proc string getChar(string $line, int $index)
{
	$index++;
	string $char = `substring $line $index $index`;
	return $char;
}

global proc getNewFilename()
{
	string $newFilename = `fileDialog -dm "~/*.lt*"`;
	print($newFilename=="");
	if($newFilename != "")
	{
		optionVar -sv lt_defaultFilename $newFilename;
		textFieldButtonGrp -e -fi $newFilename lt_filename;
	}
}

global proc getDirectory()
{
	global string $targetDirectory;
	string $targetNtDirectory;
	string $targetPathElements[];
	int $i, $pathElementsCount;
	
	fileBrowser "getTargetDirectory" "Choose Tool Path" "directory" 4;
	tokenize $targetDirectory "/" $targetPathElements;
	$pathElementsCount=size($targetPathElements);

	for ($i=0;$i<$pathElementsCount;$i++)
      		$targetNtDirectory=$targetNtDirectory+$targetPathElements[$i]+"\\";

	optionVar -sv lt_toolPath $targetNtDirectory;
	textFieldButtonGrp -e -fi $targetNtDirectory lt_toolPath;
}

global proc getTargetDirectory ( string $directory , string $type)
{
	global string $targetDirectory;
	$targetDirectory=$directory + "/";
}

global proc string getUniqueAnimName(string $filename, string $animName)
{
	int $fileId = `fopen $filename "r"`;
	if($fileId ==0) 
	{
		fclose $fileId;
		error("The programmer has failed you");			
	}

	string $line, $buffer[], $animList[];
	int  $index, $i, $len, $animNum = 0;

	while(!`feof $fileId`)
	{
		$line = `fgetline $fileId`;
		
		if(`gmatch $line "*animset*"`)
		{
			tokenize($line, "\"", $buffer);
			$animList[$animNum] = $buffer[1];
			$animNum++;
		}
	}
	string $sortedList[] = `sort $animList`;

	for($i=0; $i<$animNum; $i++)
	{		
		if($sortedList[$i] == $animName)
			$animName = $animName + "0";
	}
	fclose $fileId;
	return $animName;
}

global proc string getModelString()
{
	float $times[];
	float $keyTimes[];
	string $modelStrings[], $buffer[], $root[] = `ls -dag -type joint`;
	if((!`objExists ($root[0] + ".modelStrings")`) || (!`objExists ($root[0] + ".keyTimes")`))
		return "";
	
	string $timeString = `getAttr ($root[0] + ".keyTimes")`;
	tokenize($timeString, " ", $buffer);
	for($i = 0; $i < size($buffer); $i++)
	{
		$times[$i] = (float($buffer[$i]));
		setKeyframe -t $times[$i] ($root[0] + ".tx"); 
	}
	string $modelString = `getAttr ($root[0] + ".modelStrings")`;
	tokenize($modelString, "\"", $buffer);

	
	$j=$k=0;
	$modelString = "";
	$keyTimeString = "";
	for($i = 0; $i < size($buffer); $i++)
	{
		if(size($buffer[$j]) > 1)
		{
			$modelStrings[$k] = $buffer[$j];
			$k++;	$j++;
		}
		$j++;
	}


	
	int $j = 1;
	$keyTimes[0] = -9999;
	select -r (`ls -type animCurveTA -type animCurveTL`);

	int $stringHere;
	string $string = "\t\t\t\t(values \n\t\t\t\t\t("; 
	while($keyTimes[$j] > $keyTimes[$j-1])
	{
		for($i = 1; $i <= size($times); $i++)
		{	
			if(abs($keyTimes[$j] - $times[$i-1]) < 0.005) 
			{	$stringHere = $i;  break;	}
			else $stringHere = 0;
		}
		if($stringHere)
			$string = $string  + "\"" + $modelStrings[$stringHere-1] + "\" ";
		else 
			$string = $string + "\"\" ";
		$j++;
		$keyTimes[$j] = `findKeyframe -time $keyTimes[$j-1] -which next`;
	}
	$string = $string + " )\n\t\t\t\t)\n";
	select -cl; 
	return $string;
}

global proc findLTCconverter()
{
	$path = `optionVar -q lt_toolPath`;
	if(!`file -q -ex ($path + "LTC.exe")`)
		error("Can't proceed. Make sure the Tool Path folder contains LTC.exe\n");
}

global proc renameFile(string $infile, string $outfile)
{
	string $buffer[];
	tokenize($infile, "\\/", $buffer);
	$sysInfile = $buffer[0];
	for($i=1; $i<size($buffer); $i++)
		$sysInfile = $sysInfile + "\\\\" + $buffer[$i];
	

	tokenize($outfile, "\\/", $buffer);
	$sysOutfile = $buffer[(size($buffer) - 1)];

	$cmd = "system(\"ren \\\"" + $sysInfile + "\\\" \\\"" + $sysOutfile + "\\\"\")";
	eval($cmd);
}

global proc copyFile(string $infile, string $outfile)
{
	string $buffer[];
	tokenize($infile, "\\/", $buffer);
	$sysInfile = $buffer[0];
	for($i=1; $i<size($buffer); $i++)
		$sysInfile = $sysInfile + "\\\\" + $buffer[$i];

	tokenize($outfile, "\\/", $buffer);
	$sysOutfile = $buffer[0];
	for($i=1; $i<size($buffer); $i++)
		$sysOutfile = $sysOutfile + "\\\\" + $buffer[$i];

	$cmd = "system(\"copy \\\"" + $sysInfile + "\\\" \\\"" + $sysOutfile + "\\\"\")";
	eval($cmd);
}

global proc deleteFile(string $infile)
{
	string $buffer[];
	tokenize($infile, "\\/", $buffer);
	$sysInfile = $buffer[0];
	for($i=1; $i<size($buffer); $i++)
		$sysInfile = $sysInfile + "\\\\" + $buffer[$i];

	$cmd = "system(\"del \\\"" + $sysInfile + "\\\"\")";
	eval($cmd);
}

global proc ltaExportWithAppend(string $filename)
{
	string	$textureIndex, $sockets, $weightSets, $buffer[];
	string	$tmpFilename, $defaultAnimName, $keepfile, $ltcName;
	int	$timeRange, $looking = 0;
	float	$scale, $xDim, $yDim, $zDim;

	$fileType = `substring $filename (size($filename)-2) (size($filename))`;
	$fileBase = `substring $filename 1 (size($filename)-4)`;
	
	if($fileType == "ltc")
	{
		if(`file -q -ex ($fileBase + ".lta")`)	
			copyFile ($fileBase + ".lta") ($fileBase + "_tmpltc.lta"); 
		findLTCconverter;
		ltcConvert $filename "ltc";  
		$filename = `substitute "ltc" $filename "lta"`;
		//$keepFile = $filename;

	}
		$root = `ls -dag -type joint`;
	
		tokenize($filename, "/", $buffer);
		if(`gmatch $buffer[size($buffer)-1] "* *"`) 
		{
			if(`window -ex ltaWarningUI`)
				deleteUI ltaWarningUI;
			error("The spaces in this filename confuse me, since I'm so poorly programmed. You'll have to rename it to use me. Sorry.\n");

		}
		string $tmpAppendFilename = $filename + "_tmp.lta";
		$tmpFilename = "temp_tmp.lta";

		if(`window -ex ExportLtaUI`)
			$defaultAnimName = `textFieldGrp -q -text lt_animName`;   
		else if(`objExists ($root[0] + ".animName")`)
			$defaultAnimName = `getAttr ($root[0] + ".animName")`;
		else
			$defaultAnimName = `optionVar -q lt_defaultAnimName`;

		if($defaultAnimName == "")
			{ $defaultAnimName = "base_anim";  optionVar -sv lt_defaultAnimName "base_anim";  }
	
		$defaultAnimName = getUniqueAnimName($filename, $defaultAnimName);
		$xDim = `optionVar -q lt_defaultUserDimX`;
		$yDim = `optionVar -q lt_defaultUserDimY`;
		$zDim = `optionVar -q lt_defaultUserDimZ`;
		$scale = `optionVar -q lt_defaultScale`;
		$timeRange = `optionVar -q lt_defaultTimeRangeStatus`;
		$modelString = `getModelString`;

		float $interp = 200;
		if(`objExists ($root[0] + ".interpolation")`)
			$interp = `getAttr ($root[0] + ".interpolation")`;
//
//

		string $optionString = "scale=" + $scale + ";anim=" + $defaultAnimName + ";append=0;useAnimRange=" + $timeRange;
		copyFile $filename $tmpAppendFilename;

		int $vis[];

		$sceneShapes = `ls -ni -type mesh`;

		for($i = 0; $i < size($sceneShapes); $i ++)
		{
			$obj = `listRelatives -f -p $sceneShapes[$i]`;
			$sceneShapes[$i] = $obj[0];
			$vis[$i] = `getAttr ($sceneShapes[$i] + ".visibility")`;
			setAttr ($sceneShapes[$i] + ".visibility") 0;
		}

	file -op $optionString -typ "lta" -ea $tmpFilename;

		for($i = 0; $i < size($sceneShapes); $i ++)
		{
			setAttr ($sceneShapes[$i] + ".visibility") $vis[$i];
		}


		int $tmpAppendFileId = `fopen $tmpAppendFilename "r"`;
		if($tmpAppendFileId==0) { 
			fclose $tmpAppendFileId;
			print("An error occured... \n");  
			return;  }

		int $appendFileId = `fopen $filename "w"`;

		string $prevLine = "";
		string $nextLine = "";
		string $lastLine = `fgetline $tmpAppendFileId`;

		if($tmpAppendFileId!=0)
		{	
			while(!`feof $tmpAppendFileId`)
			{
				$prevLine = $nextLine;
				$nextLine = $lastLine;
				$lastLine = `fgetline $tmpAppendFileId`;

				if(`gmatch $lastLine "*anim-bindings*"`)
				{	
					$lastLine = $lastLine + (`fgetline $tmpAppendFileId`);
					$lastLine = $lastLine + "(anim-binding (name \""+ $defaultAnimName + "\" )(dims ("
						+ $xDim + " " + $yDim + " " + $zDim + " ))";    
					$lastLine = $lastLine + " (interp-time " + $interp + " ))\n";
				}

				fprint $appendFileId $prevLine;
			}

			if($lastLine == "")
			{
				$len = size($nextLine)-3;
				if($len >=1)
					 $bottomLine = `substring $nextLine 1 $len`+"\n";
				else $bottomLine = "";
				fprint $appendFileId $bottomLine; 
			}
			else
			{
				fprint $appendFileId $nextLine;
				$len = size($lastLine)-1;
				string $bottomLine = `substring $lastLine 1 $len`+"\n";
				fprint $appendFileId $bottomLine; 
			}
		}
		else 
		{
			print("An Error occurred\n");
			fclose $tmpAppendFileId;
			fclose $appendFileId;
			return;  
		}

		fclose $tmpAppendFileId;				
		
		string $newLine;
		$tmpFileId = `fopen $tmpFilename "r"`;
		while(!`feof $tmpFileId`)
		{
			$newLine = `fgetline $tmpFileId`;
			if(`gmatch $newLine "*animset *"`)
			{	$looking = 1;  }
			
			if(`gmatch $newLine "*on-load*"`)
			{	$looking = 0;   }


			if($looking !=0)	
				fprint $appendFileId $newLine;  

			if((`gmatch $newLine ("*" + $defaultAnimName + "\"*")`) && $looking !=0)
			{
		//	$newLine = `fgetline $tmpFileId`;
			fprint $appendFileId (`fgetline $tmpFileId`);  
		//	$newLine = `fgetline $tmpFileId`;
			fprint $appendFileId (`fgetline $tmpFileId`);  
				
			fprint $appendFileId $modelString;
			}
		}
		fclose $tmpFileId;
	
	fprint $appendFileId  ")) \n";
	fclose $appendFileId;  

	deleteFile $tmpFilename;
	deleteFile $tmpAppendFilename;

	if($fileType == "ltc")
		ltcConvert $filename "lta";

	renameFile ($fileBase + "_tmpltc.lta") ($fileBase + ".lta"); 

	if(`window -ex ExportLtaUI`)
		deleteUI ExportLtaUI;
	if(`window -ex ltaWarningUI`)
		deleteUI ltaWarningUI;
	print("Done\n");
}

global proc ltaExportNoAppend(string $filename)
{
	string $textureIndex, $sockets, $weightSets, $buffer[];
	string $sockets, $weightSets, $childModels, $keepFile, $ltcName;
	string $lastLine, $tmpFilename, $defaultAnimName, $exportJoint[];
	int  $timeRange, $socketExport;
	float $xDim, $yDim, $zDim, $scale;

	$fileType = `substring $filename (size($filename)-2) (size($filename))`;
	$fileBase = `substring $filename 1 (size($filename)-4)`;
	if($fileType == "ltc")
	{
		findLTCconverter;
		$keepFile = $filename;
		$filename = `substitute "ltc" $filename "lta"`;
		if(`file -q -ex $keepFile`) 
			deleteFile $keepFile;
		if(`file -q -ex $filename`)		
		{
			$filename = $fileBase + "tmp_del.lta"; 
			$ltcName = $fileBase + "tmp_del.ltc"; 
		}
	}
	else if($fileType != "lta")
		$filename = $filename + ".lta";

		$tmpFilename = "temp_tmp.lta";

		if(`window -ex ExportLtaUI`)
			$defaultAnimName = `textFieldGrp -q -text lt_animName`;   
		else
			$defaultAnimName = `optionVar -q lt_defaultAnimName`;

		string $root[] = `ls -dag -type joint`;

		if($defaultAnimName == "")
		{ $defaultAnimName = "default";  optionVar -sv lt_defaultAnimName "default";  }

		$scale = `optionVar -q lt_defaultScale`;
		$timeRange = `optionVar -q lt_defaultTimeRangeStatus`;
//
//
//

		string $optionString = "scale=" + $scale + ";anim=" + $defaultAnimName + ";append=0;useAnimRange=" + $timeRange;

		int $vis[]; 
		$sceneShapes = `ls -ni -type mesh`; 
		for($i = 0; $i < size($sceneShapes); $i ++) 
		{ 
			$obj = `listRelatives -f -p $sceneShapes[$i]`; 
			$sceneShapes[$i] = $obj[0]; 
			$vis[$i] = `getAttr ($sceneShapes[$i] + ".visibility")`; 
			setAttr ($sceneShapes[$i] + ".visibility") 0; 
		}
	file -op $optionString -typ "lta" -ea $tmpFilename;

		for($i = 0; $i < size($sceneShapes); $i ++) 
		{ 
			setAttr ($sceneShapes[$i] + ".visibility") $vis[$i]; 
		} 

		$xDim = `optionVar -q lt_defaultUserDimX`;
		$yDim = `optionVar -q lt_defaultUserDimY`;
		$zDim = `optionVar -q lt_defaultUserDimZ`;
		$scale = `optionVar -q lt_defaultScale`;
		$socketExport = `optionVar -q lt_defaultSocketExportStatus`;
		$exportJoint = `getSkeleton`;

		int $tmpFileId = `fopen $tmpFilename "r"`;
		int $FileId = `fopen $filename "w"`;

		if(($tmpFileId != 0) && ($FileId !=0))
		{
		int $looking = 0;
		$prevLine = "";
		$lastLine = `fgetline $tmpFileId`;
		while(!`feof $tmpFileId`)
		{
			$prevLine = $lastLine;
			$lastLine = `fgetline $tmpFileId`;
			fprint $FileId $prevLine;

			if(`gmatch $lastLine "*on-load-cmds*"`)
			{
				if(`gmatch $lastLine "*(on-load-cmds )*"`)
					$lastLine = "(on-load-cmds \n";
				$lastLine = $lastLine + "\t(anim-bindings \n\t(\n\t\t(anim-binding \n\t\t\t(name \""
							+ $defaultAnimName + "\" )\n\t\t\t(dims \n\t\t\t\t("
							+ $xDim + " " + $yDim + " " + $zDim + " ))\n";

				if(`objExists ($exportJoint[0] + ".interpolation")`)
				{
					$interp = `getAttr ($exportJoint[0] + ".interpolation")`; 
					$lastLine = $lastLine + " (interp-time " + $interp + " )\n";
				}
				$lastLine = $lastLine + ")))\n";

				if(`objExists ($exportJoint[0] + ".nodeFlags")` )
				{
					string $nodeFlags = `getAttr ($exportJoint[0] + ".nodeFlags")`;
					$lastLine = $lastLine + "\t\t(set-node-flags\n\t\t\t(\n";
					for($i = 0; $i < size($exportJoint); $i++)
					{
						$flag = `substring $nodeFlags ($i+1) ($i+1)`;
						$lastLine = $lastLine + "\t\t\t\t(\"" + $exportJoint[$i] + "\" " + $flag + " )\n";
					}
					$lastLine = $lastLine + "\t\t\t)\n\t\t)\n";
				}
	
				if(`objExists ($exportJoint[0] + ".cmdString")` )
				{	
					$cmdString = `getAttr ($exportJoint[0] + ".cmdString")`;
					$lastLine = $lastLine + "\t\t(set-command-string \"" + $cmdString + "\" )\n";
				}

				if(`objExists ($exportJoint[0] + ".childModels")` )
				{
					string $childModels = `getAttr ($exportJoint[0] + ".childModels")`;
					tokenize($childModels, " ", $buffer);
					$lastLine = $lastLine + "\t\t(add-childmodels\n\t\t\t(\n";
					for($i = 0; $i < size($buffer); $i++)
					{
						$lastLine = $lastLine + "\t\t\t\t(child-model\n\t\t\t\t\t";
						$lastLine = $lastLine + "(filename \"" + $buffer[$i] + "\" ) )\n";
					}
					$lastLine = $lastLine + "\t\t\t)\n\t\t)\n";
	
				}

				if((`objExists ($exportJoint[0] + ".sockets")`) && $socketExport)
				{
					$sockets = `getAttr ($exportJoint[0] + ".sockets")`;
					$lastLine = $lastLine + "\t\t" + $sockets + "\n";
				}

				if((`objExists ($exportJoint[0] + ".weightSets")`) && $socketExport)
				{
					$weightSets = `getAttr ($exportJoint[0] + ".weightSets")`;
					$lastLine = $lastLine + "\t\t" + $weightSets + "\n";
				}

			}

			if(`gmatch $lastLine "*shape*"`)
			{
				tokenize($lastLine, "\"", $buffer);
				$shape = `ls -type mesh $buffer[1]`;
				$piece = `listRelatives -p $shape[0]`;

				if(`objExists ($piece[0] + ".rs")`)
				{	string $rsAttr = `getAttr ($piece[0] + ".rs")`;
					tokenize($rsAttr," ",$buffer);

					$lastLine = $lastLine + "\t\t(texture-indices \n\t\t\t( ";
					for($i = 2; $i < size($buffer); $i++)
						$lastLine = $lastLine + $buffer[$i] + " "; 
					$lastLine = $lastLine + " )\n\t\t) \n";				
					$lastLine = $lastLine + "\t\t(renderstyle-index " + $buffer[0] + " )\n";
				}
			}
		}
		fprint $FileId $lastLine;
		}

		fclose $FileId;
		fclose $tmpFileId;

	if($fileType == "ltc")
	{
		ltcConvert $filename "lta"; 
		renameFile $ltcName $keepFile; 
	}

	deleteFile $tmpFilename; 

	if(`window -ex ExportLtaUI`)
		deleteUI ExportLtaUI;
	if(`window -ex ltaWarningUI`)
		deleteUI ltaWarningUI;
	print("Done\n");
}

global proc ltaWarning()
{
	$ui_Width = 255;
	$ui_Height= 125;

	if(`window -ex ltaWarningUI`)
		deleteUI ltaWarningUI;

	window
		-menuBar false 
		-maximizeButton 0
		-minimizeButton 0
		-sizeable 0
		-rtf 1
		-w $ui_Width
		-h $ui_Height
		-title "ScottTech2000"
		ltaWarningUI;
	
	columnLayout;
		frameLayout
			-label "Warning!"
			-w ($ui_Width-10)
			-h ($ui_Height-70);	
			text -label "\nYou are about to overwrite an existing file...\n" -align "center";		
		setParent ..;	
		rowLayout
			-numberOfColumns 3
			-rat 1 "top" 2
			-rat 2 "top" 2
			-rat 3 "top" 2
			-columnWidth 1 82
			-columnWidth 2 82;
			button -label "Overwrite" -al "center"
				-w 80	-h 30
				-c "string $filename = (`optionVar -q lt_defaultFilename`); ltaExportNoAppend $filename; if(`window -ex ltaWarningUI`) deleteUI ltaWarningUI;";

			button -label "Append" -al "center"
				-w 80	-h 30
				-c "string $filename = (`optionVar -q lt_defaultFilename`); ltaExportWithAppend $filename; if(`window -ex ltaWarningUI`) deleteUI ltaWarningUI;";

			button	-label "Cancel" -al "center"
				-w 80	-h 30
	//			-c "deleteUI ltaWarningUI";
				-c "string $filename = (`optionVar -q lt_defaultFilename`); getHierarchy $filename; deleteUI ltaWarningUI;";				

		setParent;
	setParent ..;

	showWindow ltaWarningUI;
}

global proc string[] getHierarchy(string $filename)
{	
	string $line, $char, $joint[], $buffer[];
	int  $index, $i, $jin[], $jout[], $looking = 0;

	int $fileId = `fopen $filename "r"`;
	if($fileId == 0) { print "Error opening file\n"; fclose $fileId; return {"",""}; }

	while(!`feof $fileId`)
	{
		$line = `fgetline $fileId`;
		if(`gmatch $line "*hierarchy*"`)
		{
			$index = 0;
			$looking = 1;
		}

		if($looking)
		{
			if(`gmatch $line "*transform*"`)
			{
				tokenize($line, "\"", $buffer);
				$joint[$index] = $buffer[1];

				$tabCount = 0;
				for($i = 0; $i <size($line); $i++)
				{
					$char = `getChar $line $i`;
					if($char == "\t") 
						$tabCount++;
					else break;
				}
				
				$joint[$index+1] = string(($tabCount-1)/3-1);	
				$index = $index + 2;
			}
			if((`gmatch $line "*shape*"`) || (`gmatch $line "*animset*"`))
			{
				break;
			}					
		}		
	}
	fclose $fileId;

	for($i = 1; $i < (size($joint)); $i=$i+2)
		$jin[($i-1)/2] = int($joint[$i]);
	$jout[0] = 0;
	for($i = 1; $i < size($jin); $i++)
	{
		if($jin[$i] != ($jin[$i-1] + 1))
		{	
			for($k = ($i-1); $k>=0; $k--)
				if($jin[$k] == ($jin[$i]-1))
				{
					$jout[$i] = $k;
					break;
				}
		}
		else
			$jout[$i] = $i-1;
		
		$joint[2*$i +1] = string($jout[$i]);
	}
		$joint[1] = "0";
		return $joint;
	}


global proc getSceneHierarchy()
{	
	string $skel[];
	$selection = `ls -sl`;
	$skelNodes = `ls -dag -type joint`;
	select -hi $skelNodes[0];
	$skel = `ls -sl -type joint`;
	print $skel;
	select -r $selection; 
}

global proc string[] getLTAInfo(string $input, string $filename)
{
	string $line, $newLine, $buffer[], $output[];
	int $searching = 0, $fileId = `fopen $filename "r"`;
	int $i = 0, $open, $close, $diff;
	if($fileId == 0)  error("Something's afoul");
	$input = "*" + $input + "*";
	$line = `fgetline $fileId`;

	while(!`feof $fileId`)
	{
		$line = `fgetline $fileId`;
	
		if(`gmatch $line $input` && !$searching)
		{
			$searching = 1;
			$open = 0;
			$close = 0;
			$output[$i] = "";	
		}

		if($searching)
		{
			tokenize($line, "\t\r\n", $buffer);
			for($chunk in $buffer)
				$newLine = $newLine + $chunk;
			$line = $newLine;
			$newLine = "";

			$open = $open + `howMany "(" $line`;
			$close = $close + `howMany ")" $line`;

			if($open <= $close)
			{
				$output[$i] = $output[$i] + $line;
				$searching = 0;
				$i++;

				if(($open < $close) && ($output[$i] != ""))
				{
					$len = size($output[$i]); 
					if(`substring $output[$i] $len $len` == " ")
						$len = $len - $close + $open + 1;
					else
						$len = $len - $close + $open;
					$output[$i] = `substring $output[$i] 1 $len`;
				}
			}
			else
				$output[$i] = $output[$i] + $line;
		}
	}
	fclose $fileId; 
	return $output;
}

global proc int howMany(string $input, string $searchString)
{
	string $buffer[];
	int $inLen, $outLen, $output;

	$input = `substring $input 1 1`;
	$inLen = size($searchString);
	$outLen = 0;
	tokenize($searchString, $input, $buffer);
		
	for($i in $buffer)
		$outLen = $outLen + size($i);
	$output = $inLen - $outLen;
	return $output;	
}

global proc setInterp()
{
	string $root[] = `ls -dag -type joint`;
	if(!`objExists ($root[0] + ".interpolation")`)
		addAttr -ln "interpolation" -at "float" $root[0];
	setAttr ($root[0] + ".interpolation") (`floatFieldGrp -q -v1 lt_interp`);
}

global proc setAnimName()
{
	string $root[] = `ls -dag -type joint`;
	if(!`objExists ($root[0] + ".animName")`)
		addAttr -ln "animName" -dt "string" $root[0];
	setAttr ($root[0] + ".animName") -type "string" (`textFieldGrp -q -text lt_animName`);
}

global proc setFileName()
{
	string $root[] = `ls -dag -type joint`;
	if(!`objExists ($root[0] + ".fileName")`)
		addAttr -ln "fileName" -dt "string" $root[0];
	setAttr ($root[0] + ".fileName") -type "string" (`textFieldButtonGrp -q -text lt_filename`);
	
}

global proc setCommandString()
{
	string $buffer[], $root[] = `ls -dag -type joint`;
	string $cmdString = `scrollField -q -text lt_cmdString`;

	tokenize($cmdString, "\n\r\t", $buffer); 
	$cmdString = "";
	for($cmd in $buffer)
		$cmdString = $cmdString + $cmd + ";"; 
	if(size($cmdString) == 1)
	{
		//$cmdString = "";
		deleteAttr ($root[0] + ".cmdString");
		return;
	}
	if(!`objExists ($root[0] + ".cmdString")`)
		addAttr -ln "cmdString" -dt "string" $root[0];
	setAttr ($root[0] + ".cmdString") -type "string" $cmdString;

}

global proc setNodeFlags()
{
	string $root[] = `getSkeleton`;
	string $nodeFlags = "1";
	for($i =1; $i < size($root); $i++)
	{	
		$flag = 2 * (`checkBox -q -v ("lt_nodeFlag" + $i)`);
		$nodeFlags = $nodeFlags + $flag;
	}

	setAttr ($root[0] + ".nodeFlags") -type "string" $nodeFlags;
}

global proc lta_Export()
{
	string $filename = `textFieldButtonGrp -q -fi lt_filename`;
	optionVar -sv lt_defaultFilename $filename;

// if file exists, append

	if(`file -q -ex $filename`)
	{
		if(`optionVar -q lt_defaultAppendStatus`)
			ltaExportWithAppend $filename;
		else 
			ltaWarning;
	}

// if file doesn't exist don't append

	else if(!(`file -q -ex $filename`))
			ltaExportNoAppend $filename;	
}



global proc maya2lta()
{
	int $ui_Width = 470;
	int $ui_Height = 250;
	string $buffer[], $textureIndex;
	string $sceneName = `file -q -sn`;
	tokenize($sceneName, ".", $buffer);
	string $scenePath = $buffer[0];
	$scene = `getSceneName`;

/////////////////////////////////////////////
// Create defaults if they don't exist
/////////////////////////////////////////////

	if(!`optionVar -ex lt_defaultFilename`)
		optionVar -sv lt_defaultFilename ($scenePath+".lta");

	if(!`optionVar -ex lt_defaultAppendStatus`)
		optionVar -iv lt_defaultAppendStatus 0;

	if(!`optionVar -ex lt_defaultTimeRangeStatus`)
		optionVar -iv lt_defaultTimeRangeStatus 1;

	if(!`optionVar -ex lt_defaultSocketExportStatus`)
		optionVar -iv lt_defaultSocketExportStatus 0;

	if(!`optionVar -ex lt_defaultUserDimX`)
		optionVar -fv lt_defaultUserDimX 128;
	if(!`optionVar -ex lt_defaultUserDimY`)
		optionVar -fv lt_defaultUserDimY 16;
	if(!`optionVar -ex lt_defaultUserDimZ`)
		optionVar -fv lt_defaultUserDimZ 16;
	if(`optionVar -q lt_defaultUserDimX` == 0)
		optionVar -fv lt_defaultUserDimX 128;
	if(`optionVar -q lt_defaultUserDimY` == 0)
		optionVar -fv lt_defaultUserDimY 16;
	if(`optionVar -q lt_defaultUserDimZ` == 0)
		optionVar -fv lt_defaultUserDimZ 16;

	if(!`optionVar -ex lt_defaultUserDimPrec`)
		optionVar -iv lt_defaultUserDimPrec 0;
	
	string $root[] = `ls -dag -type joint`;
	if($root[0] != "")
	{
		if(`objExists ($root[0] + ".dimX")`)
			optionVar -fv lt_defaultUserDimX (`getAttr ($root[0] + ".dimX")`);
		if(`objExists ($root[0] + ".dimY")`)
			optionVar -fv lt_defaultUserDimY (`getAttr ($root[0] + ".dimY")`);
		if(`objExists ($root[0] + ".dimZ")`)
			optionVar -fv lt_defaultUserDimZ (`getAttr ($root[0] + ".dimZ")`);
	}

	if(!`optionVar -ex lt_defaultScale`)
		optionVar -fv lt_defaultScale 1.0;

	if(!`optionVar -ex lt_defaultAnimName`)
		optionVar -sv lt_defaultAnimName $scene;
			
	if(!`optionVar -ex lt_toolPath`)
		optionVar -sv lt_toolPath "";


	if(`objExists ($root[0] + ".animName")`)
		$animName = `getAttr ($root[0] + ".animName")`;
	else
	{
		$animName = `optionVar -q lt_defaultAnimName`;
		addAttr -ln "animName" -dt "string" $root[0];
		setAttr ($root[0] + ".animName") -type "string" $animName;
	}


	if(`objExists ($root[0] + ".fileName")`)
		$fileName = `getAttr ($root[0] + ".fileName")`;
	else
	{
		$fileName = `optionVar -q lt_defaultFilename`;
		addAttr -ln "fileName" -dt "string" $root[0];
		setAttr ($root[0] + ".fileName") -type "string" $fileName;
	}

	
	float $interp = 200;
	if(`objExists ($root[0] + ".interpolation")`)
		$interp = `getAttr ($root[0] + ".interpolation")`;


	if(`window -ex ExportLtaUI`)
		deleteUI ExportLtaUI;
	window
		-menuBar false 
		-maximizeButton false
		-sizeable 1
		-w 5//$ui_Width
		-h 5//$ui_Height
		-rtf 1
		-title "ScottTech2000"
		ExportLtaUI;
	columnLayout;	
		frameLayout
			-label "Filename"
			-w 460
			-h 45;
			textFieldButtonGrp
				-cw 1 10
				-cw 2 390	
				-label " "
				-fi $fileName
				-cc "setFileName"
				-buttonLabel "Browse..."
				-buttonCommand getNewFilename
				lt_filename;
		setParent ..;
	rowLayout
		-numberOfColumns 2
		-cw 1 368
		-cw 2 100;	
		columnLayout;
			frameLayout
				-label "Lta Export Options"
				-w (362)
				-h ($ui_Height-50);
				columnLayout;
					textFieldGrp
						-cw 1 100
						-cw 2 200
						-label "Animation Name:" 
						-text 	$animName
						-cc 	"optionVar -sv lt_defaultAnimName (`textFieldGrp -q -text lt_animName`); setAnimName;"
						lt_animName;
					rowLayout
						-numberOfColumns 2
						-cw 1 100
						-rat 1 "top" 5
						-rat 2 "top" 5;
						text -label "Options:" -al "right";
						columnLayout;
							checkBox 
								-label "Append animation if file exists?"
								-al "right"
								-value `optionVar -q lt_defaultAppendStatus`
								-cc 	"optionVar -iv lt_defaultAppendStatus (`checkBox -q -v lt_appendCheck`)"

								lt_appendCheck;
							checkBox 
								-label "Use time slider range?"
								-al "right"
								-value `optionVar -q lt_defaultTimeRangeStatus`
								-cc 	"optionVar -iv lt_defaultTimeRangeStatus (`checkBox -q -v lt_timeRangeCheck`)"

								lt_timeRangeCheck;
							checkBox 
								-label "Export sockets/weight-sets (ignored if appending)"
								-al "right"
								-value `optionVar -q lt_defaultSocketExportStatus`
								-cc 	"optionVar -iv lt_defaultSocketExportStatus (`checkBox -q -v lt_socketExportCheck`)"

								lt_socketExportCheck;
							floatFieldGrp 
								-numberOfFields 3
								-label "User Dims (XYZ)"
								-cat 1 left 0 -cw 1 90 
								-cat 2 left 0 -cw 2 50		
								-cat 3 left 0 -cw 3 50
								-cat 4 left 0 -cw 4 50			
								-value1 `optionVar -q lt_defaultUserDimX` 
								-value2 `optionVar -q lt_defaultUserDimY` 
								-value3 `optionVar -q lt_defaultUserDimZ`
								-pre `optionVar -q lt_defaultUserDimPrec`
								-cc 	"setUserDims"
								lt_userDims;
								popupMenu;
									menuItem -l "0" -c "floatFieldGrp -e -pre 0 lt_userDims; updateUserDims; optionVar -iv lt_defaultUserDimPrec 0;";
									menuItem -l "0.0" -c "floatFieldGrp -e -pre 1 lt_userDims; updateUserDims; optionVar -iv lt_defaultUserDimPrec 1;";
									menuItem -l "0.00" -c "floatFieldGrp -e -pre 2 lt_userDims; updateUserDims; optionVar -iv lt_defaultUserDimPrec 2;";
									menuItem -l "0.000" -c "floatFieldGrp -e -pre 3 lt_userDims; updateUserDims; optionVar -iv lt_defaultUserDimPrec 3;";
							floatFieldGrp
								-numberOfFields 1
								-label "Scale"
								-cat 1 left 0 -cw 1 90
								-cat 2 left 0 -cw 2 100
								-value1 `optionVar -q lt_defaultScale`		
								-cc 	"optionVar -fv lt_defaultScale (`floatFieldGrp -q -v1 lt_scale`);"
								lt_scale;  
							floatFieldGrp
								-numberOfFields 1
								-label "Interpolation"
								-cat 1 left 0 -cw 1 90
								-cat 2 left 0 -cw 2 100
								-value1 $interp		
							//	-cc 	"optionVar -fv lt_defaultScale (`floatFieldGrp -q -v1 lt_interp`);"
								-cc	"string $root[] = `ls -dag -type joint`;
									if(!`objExists ($root[0] + \".interpolation\")`)
										addAttr -ln \"interpolation\" -at \"float\" $root[0];
									setAttr ($root[0] + \".interpolation\") (`floatFieldGrp -q -v1 lt_interp`);"
							//	-cc "setInterp"
								lt_interp;  
						setParent ..;
					setParent ..;
					textFieldButtonGrp 
						-cw 1 60
						-cw 2 240
						-label "Tool Path:" 
						-buttonLabel "Browse..."
						-bc "getDirectory"
						-fi `optionVar -q lt_toolPath`
						-cc "optionVar -sv lt_toolPath (`textFieldGrp -q -text lt_toolPath`)"
						lt_toolPath;
				setParent ..;	
			setParent ..;
			rowLayout
				-numberOfColumns 2
				-rat 1 "top" 2
				-rat 2 "top" 2
				-columnWidth 1 200;
				button  -label "Export" -w 150 -h 20 -c "lta_Export";
				button  -label "Close"  -w 150 -h 20 -c "deleteUI ExportLtaUI";
			setParent ..;
		setParent ..;
		columnLayout;
			frameLayout
				-label "Edit Options"
				-w 92
				-h ($ui_Height-50);			
				columnLayout
					-rs 2
					-cat "left" 5;
					button -label "User Dims" -w 79 -h 22 -c "showUserDims"; 
					button -label "Sockets" -w 79 -h 22 -c "editSocketWin";//"ltaImport 1"; 
					button -label "Weight Sets" -w 79 -h 22 -c "ltaImport 2"; 
					button -label "Child Models" -w 79 -h 22 -c "childModelWin"; //"ltaImport 3";
					button -label "Piece Info" -w 79 -h 22 -c "editPieceInfoWin";
					button -label "CommandString" -w 79 -h 22 -c "editCommandStringWin";
					button -label "Node Flags" -w 79 -h 22 -c "editNodeFlagsWin";
				setParent ..;
			setParent ..;
		setParent ..;
	setParent ..;			
	showWindow ExportLtaUI;
	scriptJob -p ExportLtaUI -e "SceneOpened" "optionVar -sv lt_defaultAnimName (`getSceneName`)";
	source "ltaImport.mel";
	setUserDims;
}


global proc string[] getSkeleton()
{
	string $outSkel[];
	
	string $sel[] = `ls -sl`;
	string $top[] = `ls -dag -type joint`;
	
	select -r -hi $top[0];
	string $skel[] = `ls -sl -type joint`;
	$outSkel[0] = $skel[(size($skel))-1];
	for ($i = 1; $i < size($skel); $i++)
		$outSkel[$i] = $skel[$i-1];
	
	select -r $sel;
	return $outSkel;
}


global proc editSocketWin()
{
	string $socketData[];
	if(`window -ex SocketsUI`)
		deleteUI SocketsUI;
	string $root[] = `getSkeleton`;
	

	showSockets;

	if (!`objExists ($root[0] + ".sockets")`)
		addAttr -ln "sockets" -dt "string" $root[0];
	string $currentSockets = `getAttr ($root[0] + ".sockets")`;
	tokenize($currentSockets, " ", $socketData);

	window 
		-menuBar false
		-maximizeButton false
		-w 5 
		-h 5
		-rtf 1
		-title "ScottTech2000: Sockets"
		SocketsUI;	
		columnLayout;
			paneLayout
				-w 190
				-h 140;
				textScrollList 
					-w 190
					-nr 10
					lt_socketList;
				for($i = 0; $i< (size($socketData))/8; $i++)
					textScrollList -e -append $socketData[$i * 8 + 1] lt_socketList;
			setParent ..;
			rowLayout 
				-numberOfColumns 3
				-rat 1 "top" 2
				-rat 2 "top" 2
				-rat 3 "top" 2
				-cw 1 65
				-cw 2 65
				-cw 3 65;
				button -label "Add" -w 60 -h 25 -c "addSocketWin";
				button -label "Remove" -w 60 -h 25 -c "removeSocket";
				button -label "Import" -w 60 -h 25 -c "";//"ltaImport 1";
			setParent ..;
			rowLayout 
				-numberOfColumns 3
				-rat 1 "top" 2
				-rat 2 "top" 2
				-rat 3 "top" 2
				-cw 1 65
				-cw 2 65
				-cw 3 65 ;
				button -label "Show All" -w 60 -h 25 -c "showSockets";
				button -label "Hide All" -w 60 -h 25 -c "hideSockets";
				button -label "Close" -w 60 -h 25 -c "deleteUI SocketsUI";
			setParent ..;
		setParent ..;

	showWindow SocketsUI;
}



global proc addSocketWin()
{
	string $root[] = `getSkeleton`;
	if(`window -ex AddSocketUI`)
		deleteUI AddSocketUI;

	showSockets;

	string $addJoint[] = `ls -sl`;
	int $valid = 0;
	for($i = 0; $i < size($root); $i++)
		if($root[$i] == $addJoint[0]) $valid = 1;
	if(!$valid) error("Select an exportable joint");

	window 
		-menuBar false
		-maximizeButton false
		-w 5 
		-h 5
		-rtf 1
		-title "Add Socket"
		AddSocketUI;
		columnLayout;
			columnLayout;	
				textFieldGrp 
					-cw 1 60 
					-cw 2 150 
					-label "Socket"
					-tx "NewSocket"
					-cc 	""
					lt_SocketName;
				textFieldGrp
					-cw 1 60
					-cw 2 150
					-label "Node"
					-tx $addJoint[0]
					-cc 	""
					lt_NodeName;
			setParent ..;
			rowLayout
				-numberOfColumns 2
				-rat 1 "top" 2
				-rat 2 "top" 2
				-columnWidth 1 100;
				button  -label "Add" -w 90 -h 25 -c "addSocket;";
				button  -label "Cancel"  -w 90 -h 25 -c "deleteUI AddSocketUI";
			setParent ..;
		setParent ..;
	showWindow AddSocketUI;
	
}
global proc addSocket()
{
	
	string $socketData[];
	string $root[] = `getSkeleton`;
	if (!`objExists ($root[0] + ".sockets")`)
		addAttr -ln "sockets" -dt "string" $root[0];

	
	
	
	string $currentSockets = `getAttr ($root[0] + ".sockets")`;
	tokenize($currentSockets, " ", $socketData);


	
	
	string $addJoint = `textFieldGrp -q -text lt_NodeName`;
	int $valid = 0;
	for($i = 0; $i < size($root); $i++)
		if($root[$i] == $addJoint) 
			$valid = 1;
	if(!$valid) 
		error("Select an exportable joint");


	
	
	string $addSocket = `textFieldGrp -q -text lt_SocketName`;
	$valid = 1;
	for($i = 0; $i < (size($socketData))/8; $i++)
		if($addSocket == $socketData[$i * 8 + 1]) 
			$valid = 0;
	if(!$valid) 
		error("Enter unique socket name");
	if(`objExists $addSocket`) 
		error("Socket name conflicts with existing scene object");
	

	
	spaceLocator -n $addSocket;
	parent $addSocket $addJoint;

	addAttr -ln "socket" -at bool $addSocket;
	setAttr ($addSocket + ".socket") 1;
	setAttr ($addSocket + ".translate") 0 0 0;
	setAttr ($addSocket + ".rotate") 0 0 0;
	setAttr ($addSocket + ".scale") 10 10 10;



	$currentSockets = $currentSockets + " " + $addJoint + " " + $addSocket + " 0 0 0 0 0 0";
	setAttr ($root[0] + ".sockets") -type "string" $currentSockets;
	textScrollList -e -append $addSocket lt_socketList;

	select -r $addJoint;

	deleteUI AddSocketUI;
}

global proc removeSocket()
{	
	string $socketData[];
	string $root[] = `getSkeleton`;
	string $currentSockets = `getAttr ($root[0] + ".sockets")`;
	tokenize($currentSockets, " ", $socketData);
	
	string $deleteSocket[] = `textScrollList -q -si lt_socketList`;
	int $index[] = `textScrollList -q -sii lt_socketList`;

	textScrollList -e -ri $deleteSocket[0] lt_socketList;
	delete $deleteSocket[0];

	string $newSockets = "";
	for($i = 0; $i < (size($socketData))/8; $i++)
	{
		if($i != ($index[0] - 1))
		{
			for($j = 0; $j < 8; $j++)
				$newSockets = $newSockets + $socketData[8 * $i + $j] + " ";
		}
	}

	setAttr ($root[0] + ".sockets") -type "string" $newSockets;
}

global proc showSockets()
{
	$sel = `ls -sl`;
	string $socketData[];
	string $root[] = `getSkeleton`;
	string $currentSockets = `getAttr ($root[0] + ".sockets")`;
	tokenize($currentSockets, " ", $socketData);

	for($i = 0; $i < (size($socketData))/8; $i++)
	{
		$socketName = $socketData[$i * 8 + 1];
		if(!`objExists $socketName`)
		{
			spaceLocator -n $socketName;
			parent $socketName $socketData[$i * 8];

			addAttr -ln "socket" -at bool $socketData[$i * 8 + 1];
			setAttr ($socketName + ".socket") 1;
			setAttr ($socketName + ".tx") (float($socketData[$i * 8 + 2]));
			setAttr ($socketName + ".ty") (float($socketData[$i * 8 + 3]));
			setAttr ($socketName + ".tz") (float($socketData[$i * 8 + 4]));
			setAttr ($socketName + ".rx") (float($socketData[$i * 8 + 5]));
			setAttr ($socketName + ".ry") (float($socketData[$i * 8 + 6]));
			setAttr ($socketName + ".rz") (float($socketData[$i * 8 + 7]));
			setAttr ($socketName + ".scale") 10 10 10;
		}
	}
	select -r $sel;
}

global proc hideSockets()
{	
	$sel = `ls -sl`;
	string $socketData[];
	string $root[] = `getSkeleton`;
	string $currentSockets = `getAttr ($root[0] + ".sockets")`;
	tokenize($currentSockets, " ", $socketData);

	string $newSockets = "";
	for($i = 0; $i < (size($socketData))/8; $i++)
	{
		$socketName = $socketData[$i * 8 + 1];
		$newSockets = $newSockets + $socketData[$i * 8] + " " + $socketName + " " ;
		$tx = `getAttr ($socketName + ".tx")`;
		$newSockets = $newSockets + $tx + " " ;
		$ty = `getAttr ($socketName + ".ty")`;
		$newSockets = $newSockets + $ty + " " ;
		$tz = `getAttr ($socketName + ".tz")`;
		$newSockets = $newSockets + $tz + " " ;
		$rx = `getAttr ($socketName + ".rx")`;
		$newSockets = $newSockets + $rx + " " ;
		$ry = `getAttr ($socketName + ".ry")`;
		$newSockets = $newSockets + $ry + " " ;
		$rz = `getAttr ($socketName + ".rz")`;
		$newSockets = $newSockets + $rz + " " ;
		
		delete $socketName;
	}
	setAttr ($root[0] + ".sockets") -type "string" $newSockets;
	select -r $sel;
}














global proc childModelWin()
{
	string $buffer[];
	if(`window -ex ChildModelUI`)
		deleteUI ChildModelUI;
	string $root[] = `getSkeleton`;

	if (!`objExists ($root[0] + ".childModels")`)
		addAttr -ln "childModels" -dt "string" $root[0];

	string $childModel = `getAttr ($root[0] + ".childModels")`;
	tokenize($childModel, " ", $buffer);

	window 
		-menuBar false
		-maximizeButton false
		-w 5 
		-h 5
		-rtf 1
		-title "ScottTech2000: Child Models"
		ChildModelUI;	
		columnLayout;
			paneLayout
				-w 190
				-h 140;
				textScrollList 
					-w 190
					-nr 10
					lt_childModelList;
				for($i = 0; $i< size($buffer); $i++)
					textScrollList -e -append $buffer[$i] lt_childModelList;
			setParent ..;
			rowLayout 
				-numberOfColumns 3
				-rat 1 "top" 2
				-rat 2 "top" 2
				-rat 3 "top" 2
				-cw 1 65
				-cw 2 65 
				-cw 3 65;
				button -label "Add" -w 60 -h 25 -c "addChildModel";
				button -label "Remove" -w 60 -h 25 -c "removeChildModel";
				button -label "Close" -w 60 -h 25 -c "deleteUI ChildModelUI";
			setParent ..;
		setParent ..;

	showWindow ChildModelUI;
}

global proc addChildModel()
{
	string $buffer[],$root[] = `getSkeleton`;

	string $filename = `fileDialog -directoryMask "~/*.lt*"`;
	if ( $filename == "" )
		error "No file selected";
	tokenize($filename, "\\/.", $buffer);
	$filename = $buffer[(size($buffer))-2];

	if (!`objExists ($root[0] + ".childModels")`)
		addAttr -ln "childModels" -dt "string" $root[0];
	string $childModel = `getAttr ($root[0] + ".childModels")`;
	$childModel = $childModel + $filename + " ";
	

	setAttr ($root[0] + ".childModels") -type "string" $childModel;
	textScrollList -e -append $filename lt_childModelList;
}

global proc removeChildModel()
{
	string $buffer[],$root[] = `getSkeleton`;
	string $childModel = `getAttr ($root[0] + ".childModels")`;
	tokenize($childModel, " ", $buffer);
	
	$childModel = "";
	$removeIndex = `textScrollList -q -sii lt_childModelList`;
	for($i = 0; $i<size($buffer); $i++)
		if($i != ($removeIndex[0]-1))
			$childModel = $childModel + $buffer[$i] + " ";

	setAttr ($root[0] + ".childModels") -type "string" $childModel;
	textScrollList -e -rii $removeIndex[0] lt_childModelList;
}

global proc editNodeFlagsWin()
{
	string $nodeFlags ="", $buffer[];
	if(`window -ex NodeFlagsUI`)
		deleteUI NodeFlagsUI;

	string $root[] = `getSkeleton`;

	if(!`objExists ($root[0] + ".nodeFlags")`)
	{
		addAttr -ln "nodeFlags" -dt "string" $root[0];
		for ($i = 0; $i < size($root); $i++)
			$nodeFlags = $nodeFlags + "0";
		setAttr ($root[0] + ".nodeFlags") -type "string" $nodeFlags;
	}
	else
		$nodeFlags = `getAttr ($root[0] + ".nodeFlags")`;
	window 
		-menuBar false
		-maximizeButton false
		-w 5 
		-h 5
		-rtf 1
		-title "ScottTech2000: Node Flags"
		NodeFlagsUI;	
			scrollLayout
				-h 300
				-w 270;	
				columnLayout;
					checkBox 
						-label $root[0] 
						-v 0
						("lt_nodeFlag0");
					for($i = 1; $i < size($root); $i++)
					{ 
						checkBox 
							-label $root[$i] 
							-v (int(`substring $nodeFlags ($i+1) ($i+1)`))
							-cc "setNodeFlags"
							("lt_nodeFlag" + $i);
					}
					setParent ..;
				setParent ..;
			setParent ..;
	showWindow NodeFlagsUI; 

}


global proc editCommandStringWin()
{
	string $cmdString, $buffer[];
	$root = `ls -dag -type joint`;
	if(`window -ex CmdStringUI`)
		deleteUI CmdStringUI;

	if(!`objExists ($root[0] + ".cmdString")`)
	{
		addAttr -ln "cmdString" -dt "string" $root[0];
		$cmdString = "";
	}
	else
		$cmdString = `getAttr ($root[0] + ".cmdString")`;

	tokenize($cmdString, ";", $buffer);
	$cmdString = "";
	for($cmd in $buffer)
		$cmdString = $cmdString + $cmd + "\n"; 
	window 
		-menuBar false
		-maximizeButton false
		-w 5 
		-h 5
		-rtf 1
		-title "ScottTech2000: Command String"
		CmdStringUI;	
		columnLayout;
			text -label "Edit Command String:";
			paneLayout 
				-h 120
				-w 400
				-cn "single";
				scrollField
					-wordWrap true
					-text 	$cmdString
					-c 	"setCommandString;"
					lt_cmdString;
				setParent ..;
			setParent ..;
			rowLayout
				-numberOfColumns 3
				-rat 1 "top" 2
				-rat 2 "top" 2
				-rat 3 "top" 2
				-columnWidth 1 110
				-columnWidth 2 110;
				button  -label "Enter" -w 100 -h 30 -c "setCommandString;";
				button  -label "Enter/Close"  -w 100 -h 30 -c "setCommandString; deleteUI CmdStringUI";
				button  -label "Close"  -w 100 -h 30 -c "deleteUI CmdStringUI";

	showWindow CmdStringUI;		
}




global proc editPieceInfoWin()
{
	string $rsData[], $sel[] = `ls -sl -l`;
	if (size($sel) == 0) return;
	if(`window -ex PieceInfoUI`)
		deleteUI PieceInfoUI;

	for($item in $sel)
		if(!`objExists ($item + ".rs")`)
		{ 	
			addAttr -sn "rs" -ln "renderStyles" -dt "string";
			setAttr ($item + ".rs") -type "string" "0 1 0";
		}

	string $rsAttr = `getAttr ($sel[0] + ".rs")`;
	tokenize($rsAttr," ",$rsData); 	
	for($i = 0; $i < 6; $i++)
		if($rsData[$i] == "") $rsData[$i] = "0";	

	window 
		-menuBar false
		-maximizeButton false
		-sizeable 0
		-w 5 
		-h 5
		-rtf 1
		-title "ScottTech2000: Piece Info"
		PieceInfoUI;
	columnLayout;
		frameLayout
			-label "Texture Properties"
			-w 200
			-h 120;
			columnLayout;
				optionMenu 
					-label "Number of Textures"
					-cc "updateTexIdState (`optionMenu -q -v st_numTex`)"
					st_numTex;

					menuItem -label "1";
					menuItem -label "2";
					menuItem -label "3";
					menuItem -label "4";
				text -label "\nTexture Indices:";
				rowLayout 
					-numberOfColumns 2
					-cw 1 100
					-cw 2 100;
					columnLayout;
						intFieldGrp 
							-numberOfFields 1
							-label "0:"
							-cw 1 30 -cw 2 50
							-ct2 left left 
							-co2 5 5
							-value1 (int($rsData[2]))
							st_texID1;
						intFieldGrp 
							-numberOfFields 1
							-label "2:"
							-en1 0
							-ct2 left left 
							-co2 5 5
							-cw 1 30 -cw 2 50
							-value1 (int($rsData[4]))
							st_texID3; 
					setParent ..;
					columnLayout;
						intFieldGrp 						
							-numberOfFields 1
							-label "1:"
							-en1 0
							-cw 1 30 -cw 2 50
							-ct2 left left 
							-co2 5 5
							-value1 (int($rsData[3]))
							st_texID2;
						intFieldGrp 
							-numberOfFields 1
							-label "3:"
							-en1 0
							-cw 1 30 -cw 2 50
							-ct2 left left 
							-co2 5 5
							-value1 (int($rsData[5]))
							st_texID4; 
					setParent ..;
				setParent ..; 				
			setParent ..;
		setParent ..;
		frameLayout
			-label "RenderStyle Properties"
			-w 200
			-h 40;
			intFieldGrp 
				-numberOfFields 1
				-label "     RenderStyle Index:"
				-cw 1 130 -cw 2 50
				-ct2 left left 
				-co2 5 5
				-value1 (int($rsData[0]))
				st_rsID;	
		setParent ..;
		rowLayout
			-numberOfColumns 2
			-rat 1 "top" 2
			-rat 2 "top" 2
			-columnWidth 1 100;
			button  -label "Save" -w 95 -h 20 -c "updateRenderStyles";
			button  -label "Close" -w 95 -h 20 -c "deleteUI PieceInfoUI";
		setParent ..;
	setParent ..;	
	showWindow PieceInfoUI;

	updateTexIdState $rsData[1];
//	optionMenu -e -sl (int($rsData[1])) st_numTex;
}

global proc updateTexIdState(string $num)
{	
	switch($num)
	{
		case "1": 
			intFieldGrp -e -en 0 st_texID2;
			intFieldGrp -e -en 0 st_texID3;
			intFieldGrp -e -en 0 st_texID4;
			break;
		case "2": 
			intFieldGrp -e -en 1 st_texID2;
			intFieldGrp -e -en 0 st_texID3;
			intFieldGrp -e -en 0 st_texID4;
			break;
		case "3":
			intFieldGrp -e -en 1 st_texID2;
			intFieldGrp -e -en 1 st_texID3;
			intFieldGrp -e -en 0 st_texID4;
			break;
		case "4":	
			intFieldGrp -e -en 1 st_texID2;
			intFieldGrp -e -en 1 st_texID3;
			intFieldGrp -e -en 1 st_texID4;
			break;
	}			
	optionMenu -e -sl (int($num)) st_numTex;
}

global proc updateRenderStyles()
{
	$newRenStAtt = `intFieldGrp -q -v1 st_rsID`;
	$newRenStAtt = $newRenStAtt + " " + (`optionMenu -q -v st_numTex`);
	$newRenStAtt = $newRenStAtt + " " + (`intFieldGrp -q -v1 st_texID1`);
	if(`intFieldGrp -q -en1 st_texID2`)
		$newRenStAtt = $newRenStAtt + " " + (`intFieldGrp -q -v1 st_texID2`);
	if(`intFieldGrp -q -en1 st_texID3`)
		$newRenStAtt = $newRenStAtt + " " + (`intFieldGrp -q -v1 st_texID3`);
	if(`intFieldGrp -q -en1 st_texID4`)
		$newRenStAtt = $newRenStAtt + " " + (`intFieldGrp -q -v1 st_texID4`);

	$sel = `ls -sl`;
	for($item in $sel)
		setAttr ($item + ".rs") -type "string" $newRenStAtt;
	
	deleteUI PieceInfoUI;
}

global proc ltcConvert(string $filename, string $type)
{
	string $buffer[];
	string $path = `optionVar -q lt_toolPath`;

	tokenize($path, "\\/", $buffer);
	$ltcPath = $buffer[0];
	for($i = 1;$i < size($buffer); $i++)
		$ltcPath = $ltcPath + "\\\\" + $buffer[$i];
	$ltcPath = $ltcPath + "\\\\LTC";

	tokenize($filename, "/", $buffer);
	$newFilename = $buffer[0];
	for($i = 1;$i < size($buffer); $i++)
		$newFilename = $newFilename + "\\\\" + $buffer[$i];
	
	$cmd = "system(\"" + $ltcPath + " \\\"" + $newFilename + "\\\"\")";
	evalEcho($cmd); 

	if($type == "lta")
		deleteFile $filename;
}
