

global proc string getSkinCluster(string $mesh)
{
	$history = `listHistory $mesh`;
	for($item in $history)
		if(`nodeType $item` == "skinCluster")
			return $item;
	
	return "0";
}



global proc mergePieces()
{
	string $skinClusters[], $joints[], $allJoints[];
	$sel = `filterExpand -ex 1 -sm 12`;
	$parent = `listRelatives -p $sel[0]`;

	$dupPieces = `duplicate -rr`;
	$newPiece = `polyUnite -ch 0 $dupPieces`;
	delete $dupPieces;

	for($i = 0; $i < size($sel); $i++)
	{
		$skinClusters[$i] = `getSkinCluster $sel[$i]`;
		$joints = `skinCluster -q -inf $skinClusters[$i]`;
		if($i==0)
			$allJoints = $joints;
		else
			$allJoints = `stringArrayUnion $joints $allJoints`;
	}
	
	select $newPiece[0] $allJoints;
	$newCluster = `createSkinCluster "-toSelectedBones -mi 3 -dr 4"`;
	
	setAttr ($newCluster[0] + ".normalizeWeights") false;
	clearWeights $newPiece[0] $newCluster[0];
	int $newVerts = 0;
	for($i = 0; $i < size($skinClusters); $i++)
	{
		$joints = `skinCluster -q -wi $skinClusters[$i]`;
		$numVerts = `polyEvaluate $sel[$i]`;
		
		for($j = 0; $j < $numVerts[0]; $j++)
		{
			$cmd = "skinPercent ";
			for($joint in $joints)
			{
				$weight = `skinPercent -t $joint -q $skinClusters[$i] ($sel[$i] + ".vtx[" + $j + "]")`;
				$cmd = $cmd + "-tv " + $joint + " " + $weight + " ";
			}
			$cmd = $cmd + $newCluster[0] + " " + ($newPiece[0] + ".vtx[" + $newVerts + "]");
			eval $cmd;
			$newVerts++;
		}

	}
	setAttr ($newCluster[0] + ".normalizeWeights") true;
	delete $sel;
	parent $newPiece[0] $parent[0];
	select -r $newPiece[0];
	rename $newPiece[0] $sel[0];
}


global proc clearWeights(string $piece, string $cluster)
{
	$joints = `skinCluster -q -inf $cluster`;
	int $numVerts[] = `polyEvaluate $piece`;
	setAttr ($cluster + ".normalizeWeights") false;

	for($i = 0; $i < $numVerts[0]; $i++)
	{
		$cmd = "skinPercent ";
		for($j = 0; $j < size($joints); $j++)
		{
			$cmd = $cmd + "-tv " + $joints[$j] + " 0 " ;
		}
		$cmd = $cmd + $cluster + " " + ($piece + ".vtx[" + $i + "]");
		eval( $cmd );
	}	
}

global proc string[] stringArrayUnion(string $array1[], string $array2[])
{
	string $outArray[];
	int $outSize;

	if(size($array1) > size($array2))
	{
		$outArray = $array1;
		$outSize = size($outArray);
		for($item in $array2)
		{
			$match = 0;
			for($outItem in$outArray)
			{
				if($item == $outItem)
				{
					$match = 1;
					break;	
				}
			}
			if(!$match)
			{
				$outArray[$outSize] = $item;
				$outSize++;
			}
		}
	}
	else
	{
		$outArray = $array2;
		$outSize = size($outArray);
		for($item in $array1)
		{
			$match = 0;
			for($outItem in$outArray)
			{
				if($item == $outItem)
				{
					$match = 1;
					break;	
				}
			}
			if(!$match)
			{
				$outArray[$outSize] = $item;
				$outSize++;
			}
		}
	}

	return $outArray;
}

global proc printArray(string $array[])
{
	for($item in $array)
		print($item + " ");
	print("\n");
}
