global proc unrotateJoint()

{

	string $null[];

	$sel = `ls -sl`;

	$children = `listRelatives -c $sel[0]`;



	for($i = 0; $i < size($children); $i++)

	{

		$newNull = `spaceLocator`;

		$null[$i] = $newNull[0];

		orientConstraint $children[$i] $null[$i];

		pointConstraint $children[$i] $null[$i];

		delete -constraints;	

		orientConstraint $null[$i] $children[$i];

		pointConstraint $null[$i] $children[$i];

	}



	setAttr ($sel[0] + ".rotateX") 0;

	setAttr ($sel[0] + ".rotateY") 0;

	setAttr ($sel[0] + ".rotateZ") 0;



	select -r $null;



	delete -constraints;

	delete;

}